### ISSUE TITLE
Latest VDU driver changes (Sep 24) - copy editor

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#103]
Sometimes 'Copy key' seems to work, but it often pastes garbage now.

**Comment by bobbimanners** [comment]
Have a suspicion this is related to #101

**Comment by bobbimanners** [comment]
Seems to be okay in text modes now, still funky in `MODE 2`.

**Comment by bobbimanners** [comment]
I think the problem here is we need to clear the text screen when we clear the graphics screen, since we are using the text screen as the source of the chars to copy.

**Comment by bobbimanners** [comment]
Checked in a fix to this, but also there are problems after scrolling.

**Comment by bobbimanners** [comment]
** Reverted the PR for now **

**Comment by jgharston** [comment]
COPY appears to work correctly in graphics mode now. Issue was CLS was clearing graphics buffer, but not text buffer!

**Comment by bobbimanners** [comment]
Confirmed fixed.
