### ISSUE TITLE
Enhancement idea: FDraw circles, rectangles, outline or filled

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#106]
The FDraw lib (https://github.com/fadden/fdraw) has nice routines for drawing circles and rectangles efficiently and also for filling them.  Maybe we can hook this up to some of the 'reserved' values of k for `PLOT k,x,y`.

We may also be able to get the triangle filling thing to work.  I think FDraw has a way to draw a fill arbitrary shapes (points passed in as an array.)

**Comment by jgharston** [comment]
https://mdfs.net/Software/BBCBasic/Apple/dev/tests2.po
has a suite of VDU driver tests, including graphics plot action tests. Predictably, GRAPHICS stunningly fails to draw any triangles or circles. ;)
The full list of PLOT codes are at: https://beebwiki.mdfs.net/VDU_25

What would also be useful is graphics clipping. Eg so you can MOVE 3000,500:DRAW 500,2000 and it "draws" offscreen and just the bit that crosses the visible screen is drawn. FDraw can't do clipping as its coordinates aren't large enough integers to indicate points off the screen. I think it's workable by the GFXPLOT routine doing the initial calculation and then telling FDraw to draw the  part of the line that is on-screen.

**Comment by jgharston** [comment]
There are some oddities with the translation from VDU25 to FastDraw Plot. The test program CIRCLEINT should draw random circles in random locations, but it's plotting them all centred at (0,0), and the filled circles are filling the area outside the circle instead of inside! This will probably get picked up during the tiding up of VDU.S.

I've been working out how to use horizontal line drawing primitives to implement triangle drawing - which everything else is built on - but it's rather fiddly to explain in proportional text!

**Comment by bobbimanners** [comment]
Circle drawing is implemented using `MOVE X,Y : PLOT &90+n,RADIUS,0`.

@jgharston Two questions for you ...

1) At the moment the code stupidly remembers 'RADIUS, 0' as the previous point so you have to do a `MOVE X,Y` between each circle plot, even if drawing multiple circles with the same centre.  Is this how the 'real' MOS works, or ought we to be smarter?

2) In your VDU25 page, you use the example of `PLOT 145,RADIUS,0` but this would imply relative coordinates and that doesn't make sense when the parameters are radius rather than X,Y.  `PLOT 149` works fine for circle plotting (in abs mode.)  Should the code be smarter and ignore the relative thing in this case?

I am going to do rectangle filling next.

**Comment by bobbimanners** [comment]
Drawing of filled rectangles and filled circles is now implemented.

**Comment by bobbimanners** [comment]
There is definitely a bug somewhere in the filled rectangle code (getting symptoms of a stack imbalance.)

**Comment by bobbimanners** [comment]
One issue with drawing rectangles is that the coordinates have to be presented as the top-left and bottom-right corner in Apple II coordinates, which is a bit unnatural in Beeb coordiantes (with Y increasing as you move up the screen.)

So to plot a square of edge 200, centred on x, y, this works:
`MOVE x-100,y+100 : PLOT &65, x+100,y-100`

Need to add some code to order the coordinates.

**Comment by bobbimanners** [comment]
Opened #150 and #151 to track remaining issues.  Closing this one.
