### ISSUE TITLE
Soft font pixel oddities

### ISSUE THREAD

**Issue by jgharston** [bobbimanners/Applecorn#111]
Are you wedded to the soft font being used? Some characters are a bit odd because of the 7-pixel character cells, for instance 'M' has a narrow right stem, and there are occasional colour runs from where the runs of pixels and gaps match the pixel spacing for the Apple II colour encoding.
Some characters in the font could be tweeked slightly to better match the hardware being used to display them.

Ideally, get the MOS to a state where DefChar can be used to edit them! :)

**Comment by bobbimanners** [comment]
There is a font called 'Flow' whichseems to meet the criteria.  I will try it out!

**Comment by jgharston** [comment]
On 30-09-2021 15:33, Bobbi Webber-Manners wrote:
> I am open to other fonts. This one was the first one I happened to
> try. Other people also dislike the skinny right hand stroke on M and
> W. Whatever font we choose should be good and chunky (C64-style) to
> avoid fringing/NTSC artifact colours. I do have some other fonts I
> could try.

There's a whole selection here: https://mdfs.net/Apps/Font/img/
and here: https://mdfs.net/Apps/Font/img/SysFont8x8/


-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
Ideally would like them seven pixels wide though :)

**Comment by bobbimanners** [comment]
This is Flow ...
![image](https://user-images.githubusercontent.com/11758908/135478648-d983fcf8-51b1-48d4-9789-ae3118b83e1b.png)

**Comment by bobbimanners** [comment]
![Screenshot from 2021-09-30 10-54-29](https://user-images.githubusercontent.com/11758908/135479406-d8ac50fe-0480-4d23-8c3e-0610753fd22f.png)

**Comment by bobbimanners** [comment]
One thing to be aware of is the NTSC color burst is active in HGR mode so one gets fringing on any single column of pixels.  This is not a problem in text mode where the color burst is suppressed.

**Comment by bobbimanners** [comment]
I think I prefer Flow to Clinton Turner v2 (the previous one.)

**Comment by bobbimanners** [comment]
Switched to Flow.  Let's see how we feel about this one :)

For mono monitor users (like me) we could offer a less chunky font.  NTSC artifacts are not a problem if you have a greenscreen :)

**Comment by bobbimanners** [comment]
@jgharston Like this font more?

**Comment by jgharston** [comment]
On 30-09-2021 19:57, Bobbi Webber-Manners wrote:
> @jgharston [1] Like this font more?

Yep, looks fine.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by jgharston** [comment]
On 30-09-2021 19:57, Bobbi Webber-Manners wrote:
> @jgharston [1] Like this font more?

Ooo, I'm not sure about: < > @ ^


-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
We can always tweak it later.  I quite like the `>` for the prompt :)

**Comment by bobbimanners** [comment]
Gonna close this.
