### ISSUE TITLE
Colour oddities in drawing

### ISSUE THREAD

**Issue by jgharston** [bobbimanners/Applecorn#115]
Probably a result of the Apple hardware, but this code gives unexpected results:
` 10 REM > LINES
` 20 MODE 1
` 22 GCOL 0,132:CLG
` 30 FOR X=0 TO 767
` 40 PRINT TAB(0,0);X
` 50 GCOL 0,7:REM WHITE
` 60 MOVE X,0:DRAW X,767
` 70 MOVE 0,X:DRAW 767,X
` 80 IF INKEY(5)
` 90 GCOL 0,0:REM BLACK
`100 MOVE X,0:DRAW X,767
`110 MOVE 0,X:DRAW 767,X
`120 NEXT

The vertical "white" lines are white if on the blue background, but blue or red if on the black background. Is this expected?

**Comment by bobbimanners** [comment]
'White' vertical lines will only be white if they are two pixels wide.  If they are a single pixel in width the colour depends on whether they are in odd or even columns.  Gets even more confusing when you have a background colour.  In practice things work better if the background is black.  I use a composite greenscreen and I blissfully ignore all this weirdness!  The Apple II is really a monochrome computer that can get colour ('color' really) for free using NTSC artifacts.  But quirks abound!

**Comment by bobbimanners** [comment]
I am going to close this ticket.  "It is what it is" when it comes to Apple II colour.  It's not really a colour computer, it just fakes it with smoke and mirrors :)
