### ISSUE TITLE
ISO Pascal editor - VDU issues

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#129]
In ISO Pascal, edit `edit` to start the editor and play around with it.  It seems the screen gets erased when it should not (for example, backspace erases the entire line on screen).  I expect our VDU driver needs a few tweaks.

**Comment by bobbimanners** [comment]
Had a look at this.  I think the issue is `VDU12` clears the entire screen, not just the text window.

**Comment by jgharston** [comment]
Yes, this will be fixed when I implement VDU 28. I paused on the VDU driver to dig through the filing system core. I need to have a look at PATH, then I'll go back to the VDU driver.

**Comment by bobbimanners** [comment]
Okie doke.  That is what I figured from looking at the code :)

**Comment by bobbimanners** [comment]
I think the main issue at the moment with the Pascal editor is that `CLREOL` clears the whole line, not just to EOL.  This is called when backspacing, so the entire line gets wiped out.

**Comment by bobbimanners** [comment]
I am wrong, `CLREOL` does clear to end of line, not the whole line.

**Comment by bobbimanners** [comment]
Yes, that was indeed the problem!  I have a version of `CLREOL` that does the right thing in 40 column mode.  80 column mode still needs work though.

**Comment by bobbimanners** [comment]
Confirmed Pascal editor works properly when using `CLREOL2` which is currently checked into branch `clreol`.  Once this supports the GS, it can be checked into `master` and we can close this ticket.

**Comment by bobbimanners** [comment]
ISO Pascal editor now works in both 40 and 80 column modes on //e and GS.

I still need to address `HCLREOL` so it can work in `MODE 1` too, but this is covered by ticket #154.
