### ISSUE TITLE
WILD doesn't ignore case.

### ISSUE THREAD

**Issue by jgharston** [bobbimanners/Applecorn#135]
The Apple filesystem is case insensative, LOAD "FRED" and LOAD "fred" reference the same file. However, the wildcard routines in wild.s do not ignore case so pathnames parsed by JSR WILDCARD don't match. For instance *INFO fred does not file FRED.

**Comment by bobbimanners** [comment]
Ah yes, you are right.  I forgot to go back and add case insensitivity.

[ Nice work on the extended *CAT and *EX listings by the way.  Very nice! ]
