### ISSUE TITLE
Test with /RAM3 (on //e with RamWorks) and /RAM5 (on GS)

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#139]
Last time I tried /RAM3 it didn't go well.  Need to test this again and see if I can work out what is going on.

Also be good to know it works on /RAM5 on the GS.

@jgharston Both of these things are RAMDisk drivers.  The idea is to put Applecorn and the ROMs on a RAMDisk and see how much ROM swapping is sped up.

**Comment by bobbimanners** [comment]
There is a modified and updated version of John Brooks's /RAM3 driver which I need to test.

**Comment by bobbimanners** [comment]
Appears to be in our `BRK` handler ... then escaping and running a bunch of junk in Axxx (NOPs) until it hits a `BRK` ...

**Comment by bobbimanners** [comment]
Fixed the crash with John Brooks's /RAM3 RamWorks RAMdisk driver ... with the help of Qkumba :)

Problem was the `XF2AUX` macro uses the instruction `BIT   $FF58       ; Set V: use alt ZP and LC` set set the overflow flag (which tells `XFER` to enable AltZP).

However, when the /RAM3 driver is active, sometimes AltZP is enabled so $FF58 is no longer guaranteed to contain an `RTS` which has the effect of setting V.  So V wasn't getting set, so no AltZP and chaos ensues ...

**Comment by jgharston** [comment]
On 06-11-2021 02:13, Bobbi Webber-Manners wrote:
> However, when the /RAM3 driver is active, sometimes AltZP is enabled
> so $FF58 is no longer guaranteed to contain an RTS which has the
> effect of setting V. So V wasn't getting set, so no AltZP and chaos
> ensues ...

That's why I try to use something locally I have control over in my
own code, something like:

      BIT SETV  ; Set V: use alt ZP and LC
SETV JMP XFER  ; opcode is %01001100, sets V

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
Interestingly $FF58 is a documented RTS in the ROM that is there in all versions.  ProDOS also makes sure to keep RTS at the same location in the language card.  So `BIT $FF58` is kind of canonical on the Apple II and usually safe.  However in this case it went to heck because the /RAM3 driver was banking in the AltZP (and Alt Language Card which is the same softswitch), and /RAM3 does not keep an RTS at $FF58 (maybe it should.)

So Iabelled one of our RTSs.  However if a JMP works too then I could have done that.

Anyhow ... working now :)
