### ISSUE TITLE
Strange `*DIR` behaviour with multiple sideways ROMs

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#141]
- Start Applecorn
- Select either ISO-Pascal (2 ROMs) or the multi-language (8 ROM) config
- Try `*DIR BCPL` ... takes a while but it does do it.
- Now `*DIR ..` ... hangs.  (Alternatively, `*DIR /APPLECORN` will also hang).

Repeat this test with only a single ROM loaded and it works.  I don't think this is a newly introduced bug, just one we hadn't previously noticed.

**Comment by jgharston** [comment]
Yes, I've been making notes for using absolute paths for ROMs.

**Comment by jgharston** [comment]
The issue is PATH.S has no method to refer to the current root directory. Normally you would use / to refer to the root eg. /basic.rom or /comal.rom but currently that clashes with drive selection by name eg /testprogs/basic.rom should be file basic.rom in directory testprogs in root, but currently that looks for a disk called testprogs not a directory called testprogs. Needs PATH.S updating in a while.

**Comment by bobbimanners** [comment]
I have been thinking about how best to handle this.  I wonder if we should have an `APPLECORN.CFG` config file to list all the ROM-sets in a user-configurable fashion.  This could also contain a parameter for the directory from which to load ROM files.

**Comment by jgharston** [comment]
On 04-11-2021 03:23, Bobbi Webber-Manners wrote:
> I have been thinking about how best to handle this. I wonder if we
> should have an APPLECORN.CFG config file to list all the ROM-sets in a
> user-configurable fashion. This could also contain a parameter for the
> directory from which to load ROM files.

I was pondering this as falling asleep last night.

I think it would work better if the ROM selection code is moved over to 
mainmem as it's easier to get to the mainmem file access and prefix 
code, and also some space for storing the absolute pathnames. Over the 
weekend as an initial test I'm going to see if I can move the code from 
auxmem.misc.s to maimmem.menu.s. If that works then the next step would 
be to read the prefix and pathname to the ROM images when they are 
selected in the menu, and store that absolute path for selection later.

A further option would also be your idea that on startup an 
applecorn.cfg file it checked for and if it exists it uses that for the 
ROMs.

An additional usefulness from this would be the ability to implement 
*SRLOAD. It would just need the pathname for the new "loaded" ROM to be 
stored replacing the pathname of the previous ROM.

There's space in main memory in $400-$7FF for some workspace avoiding 
the "holes" used by ProDOS, so I was looking to use that to store the 
pathnames. For example,

$400-$440 absolute pathname for ROM 0
$478-$47F ProDOS workspace
$480-$4C0 absolute pathname for ROM 1
$4F8-$4FF ProDOS workspace
$500-$540 absolute pathname for ROM 0
$578-$57F ProDOS workspace
etc.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by jgharston** [comment]
Phew! Fixed! Took a bit of mental juggling.
LOADER now uses absolute path to Applecorn startup directory for system files, including ROM files.
On my system I've renamed the Pascal files to PASCAL110A.ROM and PASCAL110B.ROM 'cos the names are so much neater ;) and match the general naming style.

**Comment by bobbimanners** [comment]
Awesome -- will take a look and merge this :)

I have been a bit distracted with craploads of $dayjob stuff recently, so I haven't gotten much Applecorn work done.

**Comment by bobbimanners** [comment]
Merged!!  Thank you very much :)

**Comment by bobbimanners** [comment]
Verified that this problem is fixed by JGH's latest PR.
