### ISSUE TITLE
Escape during `*HELP` - "Bad command" (was "Bad address" error)

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#142]
Not the correct error ;)

**Comment by jgharston** [comment]
I sometimes get Bad string. Think it's part of the pseudo-sideways ROM stuff.

**Comment by bobbimanners** [comment]
Different behaviour with the latest code ... no more error message if I hit escape during `*HELP` but Applecorn is unresponsive after returning to the prompt (no flashing cursor.)

**Comment by jgharston** [comment]
Reproduced! Wonder what's causing it. GSPLUS's status line says: Emulated system state probably corrupt. and the status monitor is continuously scrolling: UNIMP READ to addr 0000009b.

**Comment by bobbimanners** [comment]
It would be nice if Escape could interrupt *HELP seeing as it can take so long with 8+ ROMs loaded.  (However, I will settle for not crashing, lol!)

**Comment by bobbimanners** [comment]
Also get some weirdness happening if I hit Escape when `*CAT` is underway, for example.  I am guessing this may be something to do with being in main memory at the time.  Perhaps.

**Comment by bobbimanners** [comment]
If I do this in MAME, hitting Escape during `*HELP` just causes a freeze up after the BASIC prompt is printed.  It is interesting that this behaves differnently on GS and //e, and I wonder if fixing this may fix some of the other reported weirdness on GS.  I have no idea what is going on though.  However it does appear to be getting stuck in code around location 37B8, which I assume is in main memory.  As far as I am aware there should be Applecorn code here, so it seems to be jumping into never-never land.

**Comment by bobbimanners** [comment]
Problem is happening here (using the trace dump function in MAME):

```
* VBLK pulses at 50Hz/60Hz, toggles at 100Hz/120Hz
             LDX   $C019                     ; Get initial VBLK state
INKEY8       BIT   $C000
             BMI   INKEY4                    ; Key pressed
             TXA
             EOR   $C019
             BPL   INKEY8                    ; Wait for VBLK change
             BMI   INKEYLP                   ; Loop back to key test

INKEYOUT     PLA                             ; Drop stacked Y
             LDA   #$FF                      ; Prepare to stack $FF
*
INKEYOK      PHA                             ; Save key or timeout
             PHP                             ; Save CC=key, CS=timeout
             LDA   OLDCHAR                   ; Prepare for main cursor
             BIT   VDUSTATUS
             BVC   INKEYOFF2                 ; No editing cursor
             JSR   PUTCHRC                   ; Remove cursor
             JSR   COPYSWAP1                 ; Swap cursor back
             LDA   COPYCHAR                  ; Remove main cursor
INKEYOFF2    JSR   PUTCHRC                   ; Remove cursor
*
             PLP
             BCS   INKEYOK3                  ; Timeout
             LDA   ESCFLAG                   ; Keypress, test for Escape
             ASL   A                         ; Cy=Escape flag
             PLA                             ; Get char back
             PLX                             ; Restore X,Y for key pressed
INKEYOK3     PLY                             ; Or pop TimeOut
             RTS
```

The RTS at the end is jumping off to a crazy address.  I suspect the pushes and pops are imbalanced somehow in the code path where Escape has been pressed.  Investigating.

**Comment by bobbimanners** [comment]
Fixed.  Moved the label `INKEYOK3` up two instuctions (before the `PLA`)

**Comment by bobbimanners** [comment]
Unfortunately, this fix breaks the Pascal editor, so there is something more subtle going on.  No good deed goes unpunished ;)

**Comment by bobbimanners** [comment]
I think with `*HELP` being so slow we have a case where there ESCFLAG is set but there is also a timeout.

**Comment by bobbimanners** [comment]
If I do `*FX 200,1` before `*HELP` then escape is disabled and we circumvent this issue.

**Comment by bobbimanners** [comment]
Jonathan, can you take a look at this one.  I don't think I understand `*HELP` / the service ROM stuff properly.

**Comment by bobbimanners** [comment]
With the changes made for ticket #157, this issue may have been fixed.  Hitting Escape during `*HELP` now returns to the prompt.  Hitting Return gives 'Bad Command' so maybe the Escape is in the buffer still?  I am not getting random errors any more.

**Comment by bobbimanners** [comment]
Consistently 'Bad Command' on //e and GS.  Will update the title.

**Comment by bobbimanners** [comment]
Fixed in `INKEY`.  Adjusted branch destination if `ESCFLAG` is set to skip over `PHA` and `PHP`.  (See label `INKEYXXX`).

**Comment by bobbimanners** [comment]
Nope.  This is still not fixed!!

**Comment by bobbimanners** [comment]
Seems to work fine except when the language is Pascal.  May be a bug in the Pascal ROMs perhaps.  Or something peculiar to the fact that Pascal is the only language we support that is on two ROMs.

**Comment by jgharston** [comment]
On 24-09-2022 21:16, Bobbi Webber-Manners wrote:
> Nope. This is still not fixed!!

I'll have a look at this over the weekend. I've been
concentrating on optimising the loating point divide
code for the PDP11.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
The only way I can make it fail right now is:

1) Select the option for all eight language ROMs
2) *PASCAL
3) *HELP, then Escape.

It seems to be fine if the active language is not Pascal!

All the best,
Bobbi

**Comment by jgharston** [comment]
So far:
The only things that call KBDCHKESC are:
* the low level key read code
* the VDU driver when printing a character
* the VDU driver when doing a PLOT
None of those have any path problems.

The trace in MAME shows it falling over with INKEY. So, what's calling INKEY? And how is that happening during *HELP? Checking the next layer up....

**Comment by bobbimanners** [comment]
I think `INKEY` is getting called once we get back to the BASIC prompt after `*HELP` completes.

**Comment by jgharston** [comment]
Odd, I've been working on this this evening and can't replicate it on KEGS and AppleWin both on Windows. Have you got a disk image with the build that falls over?

**Comment by bobbimanners** [comment]
I think it is still happening with the latest .po file from Github.  Sometimes I think I have fixed it, but it always rears its ugly head occasionally ;)

**Comment by bobbimanners** [comment]
This is still a thing.  Just saw it today with the latest build in `main`.

**Comment by jgharston** [comment]
On 10-10-2022 06:05, Bobbi Webber-Manners wrote:
> This is still a thing. Just saw it today with the latest build in
> main.

Will have a look at it at the weekend. I've got some thoughts where
it might be happening.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by jgharston** [comment]
Satisfied with character input, will concentrate on this next.

**Comment by bobbimanners** [comment]
Excellent :)

**Comment by jgharston** [comment]
Added a debug test in service code. Try *OPT255,32 and see if the problem goes away.

**Comment by jgharston** [comment]
Ah ha! I've finally got it to fall over! I can try and track it down now. See
https://mdfs.net/Software/BBCBasic/Apple/img/demo11.gif

**Comment by bobbimanners** [comment]
Any luck?  This is such a flighty bug!

**Comment by jgharston** [comment]
I've narrowed it down. It only happens if Pascal is the current language, and only if Pascal is present. Removing all other ROMs (including BASIC) does not prevent it.

**Comment by bobbimanners** [comment]
That is interesting.  It makes me wonder if perhaps Pascal is the only one of the ROMs we have tried which depends on a certain register being preserved which we could be trashing.  Perhaps.

**Comment by bobbimanners** [comment]
Excellent work!!

**Comment by bobbimanners** [comment]
@jgharston Any progress?

**Comment by jgharston** [comment]
On 30-10-2022 22:18, Bobbi Webber-Manners wrote:
> @jgharston [1] Any progress?

I think so. After several hours single-stepping through code
I think I've tracked it down.

If RDKEY is entered when an Escape state already exists, then
on the first pass, Carry is undefined, and the loop exits
early, and pops the wrong amount, resulting in it RTS'ing
to zero page and crashing data and executing it as random
code. In conjunction, when stuck in this loop, the keyboard
isn't cleared, so the next read thinks the Escape state is
still there, setting the loop off again.

You can actually trigger it in any language by typing *FX125.

It needs one additional CLC to RDKEY, and a slight change
to BYTE7E. I need to remove the debug code, sync my
repository, and upload the update.

Phew!

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
Woohoo!  Nice job finding that!!

**Comment by bobbimanners** [comment]
JGH's PR is merged.  Closing this ticket.
