### ISSUE TITLE
Applecorn crashing on launch from hard drive

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#146]
Runs on real //e from VEDrive but when I copy it to a directory on my hard drive it is not happy.

I get the ROM selection menu but when I make a selection it prints inverse video flashing exclamation marks forever.

@jgharston Tagged you for your information.  I am not sure where this is going wrong yet.  It will be a pain to diagnose if it only happens on the real hardware.

**Comment by bobbimanners** [comment]
Duplicate `:L1B` label in `MAINMEM.LDR.S` line 148 could be the culprit!

**Comment by bobbimanners** [comment]
That does improve things, but still have issues.

**Comment by bobbimanners** [comment]
![image](https://user-images.githubusercontent.com/11758908/141656795-5661fbc1-f7e0-4997-90e9-395991ba46d5.png)

**Comment by bobbimanners** [comment]
Clearly the prefix is either not getting determined properly or is getting corrupted.

**Comment by bobbimanners** [comment]
The problem occurs whenever there is more than one level of directories.  If I create a subdir on the floppy and copy Applecorn, the ROMs, FDRAW.FAST and FONT.DAT there, I get the same failure launching it in the subdir.

Good news!  I can reproduce this in MAME.

**Comment by bobbimanners** [comment]
Problem is in `LOADCODE`.

**Comment by bobbimanners** [comment]
I am running Applecorn from dir `/APPLECORN/TEST`.  Start it from `BASIC.SYSTEM` using `-APPLECORN`.  On entering `LOADCODE`, `CMDBUF` (0x280) has "APPLECORN".  It is copied to `MOSFILE2`, then this ...

```
:LP2        DEX
            LDA   MOSFILE2+1,X
            CMP   #'/'
            BNE   :LP2
```
This is not going to go well seeing as `MOSFILE` does not have a '/'.

**Comment by bobbimanners** [comment]
Confirmed if I start Applecorn with an explicit absolute path, all is well:
```
PREFIX /APPLECORN/TEST
-/APPLECORN/TEST/APPLECORN
```
So the problem occurs when there is no absolute path in 0x280 (which is not guaranteed.)  I believe we correctly set the prefix on startup, so maybe we should stash it somewhere are use that, just forget about 0x280 (`CMDBUF`).

**Comment by jgharston** [comment]
On 13-11-2021 19:52, Bobbi Webber-Manners wrote:
> The problem occurs whenever there is more than one level of
> directories. If I create a subdir on the floppy and copy Applecorn,
> the ROMs, FDRAW.FAST and FONT.DAT there, I get the same failure
> launching it in the subdir.
> 
> Good news! I can reproduce this in MAME.

I spent all day today getting MAME working, so that's useful.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
This is the command line I use for MAME:
```
mame -debug -w apple2ee -sl7 cffa202 -hard1 ./applecorn.po
```

**Comment by jgharston** [comment]
On 13-11-2021 20:31, Bobbi Webber-Manners wrote:
> Confirmed if I start Applecorn with an explicit absolute path, all is
> well:
> 
> PREFIX /APPLECORN/TEST
> -/APPLECORN/TEST/APPLECORN
> 
> So the problem occurs when there is no absolute path in 0x280 (which
> is not guaranteed.) I believe we correctly set the prefix on startup,
> so maybe we should stash it somewhere are use that, just forget about
> 0x280 (CMDBUF).

All my testing had shown CMDBUF holding the full absolute path eg
/TESTDISK1/APPLECORN

So your testing shows that with a relative path, eg:
] BRUN APPLECORN

sometimes CMDBUF does not have the absolute path, but with an absolute
path, eg:
] BRUN /APPLECORN/PROJECTS/APPLECORN

CMDBUF always has an absolute path? That looks like there is a simple 
fix,
if the path at CMDBUF is not an absolute one (doesn't start with / - 
nice
easy test), it has been run from the current prefix so read the current
prefix to CMDBUF.

A quick temporary fix might be:
:LP2        DEX
             BEQ   :L4 ; no '/' found, use plain path
             LDA   MOSFILE2+1,X


-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
Yes I think it is easy to fix.  One thing I thought to do was to have the `SETPRFX` write the absolute path (or the prefix) to `CMDBUF`.

**Comment by jgharston** [comment]
Ok, I've had a dug around, and I think I know where to put the code. I'll put the kettle on.

Steptoe & Son marathon on the radio tonight. ;)

**Comment by bobbimanners** [comment]
Steptoe and Son is going back a bit!  I will leave this one to you then :)  Maybe I try and investigate why Logo is mad at us.  I have to go out shortly, so most likely won't get back to this until tomorrow.

**Comment by jgharston** [comment]
Added: If startup command line absent, reads prefix, as must have been started from current directory.
This seems to fix it here. Using GSPLUS with all the applecorn files in /DISK1/ACORN the following all work:
prefix acorn
brun applecorn

brun acorn/applecorn

brun /disk1/acorn/applecorn

prefix /testdisk2/
brun /disk1/acorn/applecorn

prefix /disk1/bcpl
brun /disk1/acorn/applecorn

:)

**Comment by jgharston** [comment]
I've also tweeked *ROMS so it ignores top-bit-set characters, as the Pascal ROMs all had unterminated strings in the header:
![image](https://user-images.githubusercontent.com/17123287/141693243-2652b8b1-b4a0-40b7-a150-8382eb2b582a.png)

**Comment by bobbimanners** [comment]
Merged!!  Seems to work fine.

**Comment by bobbimanners** [comment]
@jgharston I don't think you merged the `*ROMS` command though.  Gives me "Bad command".

**Comment by bobbimanners** [comment]
Just occured to me, you `*ROMS` is probably an on-disk command?
