### ISSUE TITLE
Source code arrangement

### ISSUE THREAD

**Issue by jgharston** [bobbimanners/Applecorn#16]
It mighty be worth splitting the source code into functional blocks, so separate bits can be worked on. Eg (approximately mirroring the Beeb):
startup - $2000 onwards, getting everything into place
hostcode - the code that lives in main memory to access the apple monitor and I/O
vdutext - code from $D000 onwards in the aux memory
vdugraph
filing
keyboard
kernel

**Comment by bobbimanners** [comment]
Yes I agree.  It is a bit rough and ready right now.  I may actually split it into multiple files.  It is getting slow to assemble natively on the Apple //e (even with my 13MHz accelerator :) )

**Comment by bobbimanners** [comment]
As of 5 minutes ago, I am 'OUT OF MEMORY' in the Merlin-8 editor, so time to split it up!

**Comment by bobbimanners** [comment]
Split code into multiple files:

- `applecorn.s` is the main program that includes all the others using the `PUT` directive
- `loader.s` is the code that loads the ROM from disk into aux memory
- `mainmem.s` is the code that resides in Apple //e main memory and serves as glue between the 'virtual BBC Micro' in aux memory and the ProDOS MLI API.
- `auxmem.s` is the Acorn MOS interface which resides in Apple //e aux memory.

I plan to break this up further as the project develops.
