### ISSUE TITLE
Refactor to make into .SYSTEM program

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#161]

**Comment by apple2geek** [comment]
Proposed starting point for an APLCORN.SYSTEM committed into branch `system`.
As long as there are no show-stoppers, once this gets merged, Applecorn can/will become a .SYSTEM going forward, freeing up a lot more space for new features and easy growth of the code base in general.

**Comment by apple2geek** [comment]
Base conversion to .SYSTEM is complete.  Further improvements are now available to reclaim some of the slack space in the current .SYSTEM implementation.
