### ISSUE TITLE
Reclaim substantial slack space in APLCORN.SYSTEM

### ISSUE THREAD

**Issue by apple2geek** [bobbimanners/Applecorn#170]
The transition to APLCORN.SYSTEM resulted in a large gap of unused space - close to 8K both in RAM and on disk - between the base loader code at $2000 and the start of the main-memory-resident code at $4000.  This was required because the main-memory-resident code needed to remain untouched by HGR1 operations.

There is a substantial block of code further up in memory that does not stay resident long-term.  It is either single-use code in main, or code that is transferred wholesale to AUX memory for operation there.  Relocating these categories of code into the gap between the base loader code and the main-memory-resident code will eliminate this "slack" space, reduce the on-disk size of the APLCORN.SYSTEM binary, and bring the top end of the code in memory down, freeing up space for future features and enhancements, or for possible additional I/O buffers.

**Comment by jgharston** [comment]
Good idea.

**Comment by apple2geek** [comment]
Several commits/PRs related to this have been applied to `main`.
All the auxmem.*.s files were brought to the head of the build, just after mainmem.ldr.s, and all the remaining mainmem.*.s files were relocated behind the auxmem ones.
A new `ORG` directive for the mainmem portion was required to get the code to align correctly, but the end result is a tightly-packed 15.6K binary .SYSTEM file that now ends at $5CF6, leaving essentially 25K of usable space for the FONT, FASTDRAW, I/O buffers, and future features and enhancements.
