### ISSUE TITLE
Interrupts masked in INKEY

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#177]
Discovered this while investigating a problem with the new Ensoniq audio implementation (which still lives in the `ensoniq` branch at present).  Sometimes the audio code would completely stop working, including not terminating notes that were currently playing.  This seemed consistent with the ISR (`ENSQISR`) not being called.

Investigated with the MAME debugger and found that code was looping within `INKEY` with interrupts masked, so the ISR was not being called.  For now I insterted a `CLI` instruction here:

```
*
* VBLK pulses at 50Hz/60Hz, toggles at 100Hz/120Hz
             LDX   $C019                     ; Get initial VBLK state
INKEY8       BIT   $C000
             CLI                             ; DIRTY HACK TO GET ENSONIQ TO WORK
             BMI   INKEY4                    ; Key pressed
             TXA
             EOR   $C019
             BPL   INKEY8                    ; Wait for VBLK change
             BMI   INKEYLP                   ; Loop back to key test

```

However this is clearly not the correct long term solution!  I am not sure which part of the code is failing to re-enable interrupts.  However I don't think it is any of the new Ensoniq stuff in `mainmem.audio.s`.

**Comment by bobbimanners** [comment]
@jgharston You may be interested in this one!

**Comment by jgharston** [comment]
I've been pondering this. On the BBC:
INKEY enables IRQs then waits for a key, then restores IRQs via the OSBYTE handler.
RDLINE enables IRQs then calls OSRDCH, then restores IRQs via the OSWORD handler.
RDCH never changes IRQs, then waits for a key. So, SEI:JSR OSRDCH will result in the computer looping forever.

My feeling is that OSRDCH should ensure IRQs are enabled, and have added a *BUG* comment to my BBC disassembly.
But also, in line with the rest of the API, it should restore IRQs to whatever they were when OSRDCH was called.
I'll work out the code, and type it up at the weekend.

**Comment by bobbimanners** [comment]
One thing to maybe consider.  I am implementing support for the Ensoniq audio in the Apple IIgs (in branch `ensoniq`).  The Ensoniq can generate interrupts, so I have an interrupt-driven audio state machine similar to the Beeb's.  On the //e I plan to add support for Mockingboard audio, which also can generate interrupts.  (However, Mockingboard is an optional add on and we still have to function without it.)

I have been vaguely considering whether it is worth having a keyboard buffer on those systems where there is an interrupt source.  On the other hand, we have to make everything work without asynchronous keyboard handling, and supporting both may be a horrible idea.

I plan to merge `ensoniq` into `main` soon.  You may want to tinker with it a bit.  It is mostly complete, except I have not yet done anything about `ENVELOPE`.  I want to get the rest of the audio stabilized before I worry about that.

**Comment by jgharston** [comment]
Bobbi Webber-Manners wrote:
> I have been vaguely considering whether it is worth having a keyboard
> buffer on those systems where there is an interrupt source. On the

Yes, I'd been pondering moving to background interupt-driven keyboard
processing. But, of the IIc, IIe and IIgs, do all of them have a ticker
interupt? I had a thought that a ticker interupt wasn't universal.

At the moment, foreground keyboard processing is working, and moving it
into the background would also introduce fiddly work with the soft
flashing cursor. I think we can leave it for the moment.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
The IIgs has a VBL interrupt (or you can use the Ensoniq).  I *think* the //c has a VBL interrupt.  The //e, however, has no interrupt source at all.

I agree, we leave it in the foreground for now.  Could get very fiddly indeed to support both mechanisms.

**Comment by bobbimanners** [comment]
@jgharston I merged the Ensoniq audio stuff into `main`.

**Comment by jgharston** [comment]
I think I've sorted the character input IRQ issue to my satisfaction. I'm grumpy that OSRDCH doesn't preserve the IRQ status as all other calls do, but I think it's acceptable. Trying to preserve it would involve some complicated stack shuffling.

**Comment by bobbimanners** [comment]
Awesome - is that in the PR I just merged?

**Comment by jgharston** [comment]
I've just done a Sync and Diff and it's identical, so: Yes. :)

**Comment by bobbimanners** [comment]
Awesome - that is reassuring :)

**Comment by bobbimanners** [comment]
@jgharston Can we close this ticket, or is there still stuff to do?

**Comment by jgharston** [comment]
I would close it, but I can't find a Close button.

**Comment by bobbimanners** [comment]
Maybe only I can close issues ... not sure.  Anyhow, closed!!
