### ISSUE TITLE
Screen editor (like BBC Micro Copy key)

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#18]
Need to implement a screen editor.  Getting fed up with retyping BASIC lines ;)

**Comment by jgharston** [comment]
I've been thinking about this, but the problem being what key to use for COPY.

Plus irritating problems with the keyboard being a raw ASCII I/O port, you can't see the state of the SHIFT and CTRL keys, and BackSpace and LeftArrow both generating the same character code.

**Comment by bobbimanners** [comment]
I think the way to do this is to use the Open Apple and Closed Apple keys, which are actually wired to the game port (like joystick buttons) rather than the keyboard encode.  Open Apple + Right Arrow would be an obvious choice for Copy.

**Comment by jgharston** [comment]
Do you know how common it is to have the "wired Shift" modification where the state of the Shift keys is visible as I/O bit 2? With the Apple keys that means there's effectively three modifier keys that can be read, emulators usually map the two Apples to the two ALT keys.
(What would be more useful is a "wired Ctrl", then you can tell apart Ctrl-H and LEFT, Ctrl-J and DOWN, etc.)

**Comment by bobbimanners** [comment]
There was a hack on the Apple ][+ called "one wire shift key mod" or something similar which basically wires the shift keys to a switch input on the game port.  That was quite common for users with 80 column cards who could display (gasp!) lower case text.

The //e incorporates 80 cols and also has a way better keyboard.  The Open and Closed Apple keys are wired to the game port in a similar manner.  I don't know if there is a way to detect shift key down on the //e, but I think not.

The Apple II keyboard is pretty simplistic (data and strobe at $C000, and $C010 resets the strobe.)  There is no buffer.  And no way to detect multiple keys down or even key held.

**Comment by jgharston** [comment]
Having a bit of a look at this. The Apple cursor keys return insane values. 8, 10, 11 and.... 21! So pressing RIGHT is the same as Ctrl-U = delete line.

So, I was thinking of using an Apple key as a modifier. My thoughts are:
If we define Apple+cursors means the cursor keys are cursor keys then Ctrl-U is delete line and Apple-Right is right cursor. But that's counter intuituve, I'm sure it will get annoying forgetting to press Apple-Right and accidently just pressing Right and getting a Ctrl-U.
So, if we define that Apple+ControlCharacter is "real" control characters and no-Apple is cursor keys, then the cursor keys can be pressed without accidently doing a Ctrl-U, and you need to do Apple-U to do a delete-line. If you forget and press Ctrl-U you get a harmless RightCursor, which I think is less annoying than forgetting and RIGHT accidently doing a destructive DeleteLine.

**Comment by bobbimanners** [comment]
I think this can be closed now.  Copy functionality (using Tab key for Copy) is working now.
