### ISSUE TITLE
Implement `*TV` as a no-op

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#187]
Lots of BBC BASIC programs call `*TV`.  It doesn't need to do anything, but nice if it wasn't an error.

There are also some `*FX` calls we may want dummies for also.

**Comment by jgharston** [comment]
Will do this one.

**Comment by bobbimanners** [comment]
Awesome, thanks!

**Comment by bobbimanners** [comment]
I merged the code.  Forgot to close the ticket.
