### ISSUE TITLE
FORTH corrupts language workspace

### ISSUE THREAD

**Issue by jgharston** [bobbimanners/Applecorn#192]
FORTH103 corrupts language workspace during *HELP. Try this:
With FORTH103 present
> *BASIC
> *HELP
> MODE 7
Bad MODE

I've been tearing my hair out all day trying to find what was going wrong with Applecorn.... until I isolated it to FORTH103. WT$$%%%!!$$##$$!!!! I'm going to patch the FORTH ROM, as this is a critial flaw with it, it will kill anything else that is in the same machine as it.

**Comment by bobbimanners** [comment]
Yes, I can verify that here.  Applecorn has been finding lots of bugs in various Apple II emulators ... and also in Acornsoft ROMs now.

Reminds me ... would it be trivial or painful to also fix the poor coding in the Logo ROMs which prevent it working with Applecorn?  Or not worth the faff?

**Comment by jgharston** [comment]
On 07-11-2022 02:34, Bobbi Webber-Manners wrote:
> Reminds me ... would it be trivial or painful to also fix the poor
> coding in the Logo ROMs which prevent it working with Applecorn? Or
> not worth the faff?

I'll make a note to have a look at those.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by jgharston** [comment]
Fixed.

**Comment by bobbimanners** [comment]
The updated FORTH seems to work fine as a secondary language but doesn't initialize properly if it is the default language on boot.  (Pick 8 on the menu for all ROMs, then `*FORTH` from BASIC appears to be fine.  However, if you just boot with Forth as the only ROM, it doesn't get to the prompt.)

**Comment by jgharston** [comment]
On 08-11-2022 01:04, Bobbi Webber-Manners wrote:
> The updated FORTH seems to work fine as a secondary language but
> doesn't initialize properly if it is the default language on boot.

Odd, it works on the BBC and Master as the default language.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
Also, I notice when I `*FORTH` it doesn't ask me if I want to warm or cold start.  Maybe that is a hint.

**Comment by jgharston** [comment]
Yes that was the hint. Applecorn always claims it's a Soft Break, FORTH needs at least one Hard Break to initialise. It thought it was being entered from a Soft Break and trying to do its version of OLD - without any data to recover. I've temporarily set the BreakFlag to Hard on every startup. I did start coding this properly, but it was when we weren't copying the right amount of code into high memory, and it kept dying because part of the code was being missed off. I'll make a note to add it properly.

**Comment by bobbimanners** [comment]
Could you do me a favour and email me the latest Forth ROM with the fix.  I am having a bit of a fight with Git here!

**Comment by bobbimanners** [comment]
Found it, don't worry!

**Comment by bobbimanners** [comment]
Confitmed that the patched Forth fixes the workspace corruption problem.  Closing.
