### ISSUE TITLE
Implement `*CODE` and `*LINE`

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#211]
These should be fairly trivial I think  @jgharston  ??

I think 'Chariots of Fire' uses `*CODE` which is my motivation for implementing it.

**Comment by jgharston** [comment]
On 06-12-2022 01:49, Bobbi Webber-Manners wrote:
> These should be fairly trivial I think @jgharston [1] ??

They are implemented, they just jump to USERV with A set appropriately.

(Checks...) Ah, *LINE isn't, I'll add it. It's just a jump to JMP 
(USERV).

> I think 'Chariots of Fire' uses *CODE which is my motivation for
> implementing it.

Ah! Are you also going to put an SN76489 in the I/O map so it can be
frobbed? Chariots accesses the sound hardware directly! :D

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh
