### ISSUE TITLE
Implement something for `*TITLE`

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#213]
BBC ADFS allows directories to have both a name and a 'title'.  This is not currently implemented in Applecorn.  `*TITLE` currently just returns "Bad command".

**Comment by bobbimanners** [comment]
One obvious way to implement this is to have an optional file in each directory into which to record the directory title.  Applecorn could hide it in directory listings.  Seems like an ugly feature and a lot of work for very little utility.

**Comment by jgharston** [comment]
PrDOS implements disk titles, so pass it straight on.

**Comment by bobbimanners** [comment]
I think for ProDOS the 'disk title' is just the name of the volume (root) directory, unless I am missing something.

**Comment by jgharston** [comment]
On 11-12-2022 03:15, Bobbi Webber-Manners wrote:
> I think for ProDOS the 'disk title' is just the name of the volume
> (root) directory, unless I am missing something.

Yep, disk title.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
I guess I was thinking of ADFS which is what I am copying the semantics of more than DFS ...

And in ADFS, `*TITLE` can be used to title any subdirectory, unless I am mistaken.  So each subdir (including the root dir) can have both a name and a title.  So we would need to store the title somewhere.

**Comment by jgharston** [comment]
On 11-12-2022 21:59, Bobbi Webber-Manners wrote:
> I guess I was thinking of ADFS which is what I am copying the
> semantics of more than DFS ...
> 
> And in ADFS, *TITLE can be used to title any subdirectory, unless I am
> mistaken. So each subdir (including the root dir) can have both a name
> and a title. So we would need to store the title somewhere.

Yes, that's an anomoly. A disk should have one title, 8-bit ADFS
is the oddball here. The caconical symantics is that *TITLE sets
the disk's title. Every other filing system, and on non-8bit
systems, the thing written with *TITLE and read with OSGBPB 5 is
the title of the disk.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
OK, so maybe we depart from 8-bit ADFS semantics here then ;)

I will make it set the volume directory name then.  Can be done with `*RENAME` at the moment, if you know the old name (or physical drive number.)

**Comment by bobbimanners** [comment]
I have implemented `*DTITLE`, which supports two ways of working:

1) `*DTITLE <drv> <title>` - So this could be `*DTITLE :71 FOOBAR` or `*DTITLE /H1 FOOBAR`.
2) `*DTITLE <title>` - Which assumes the current drive.

I had to make it `*DTITLE` rather than just `*TITLE` because for some reason `*TITLE` does not parse -> "Bad command"  @jgharston Any ideas?

If you rename the current disk, you will have to `*DIR` or `*DRIVE` again because the old prefix is still in effect.  Not sure if this is really a problem worth addressing.

**Comment by jgharston** [comment]
Bizzare! I'm getting exatly the same. I even changed it to *MICHAEL and it called the test code, changing back to *TITLE and CLILOOKUP returns 'not found'. Weird. I think I'm going to have to do some single-stepping and track down what on earth is going on.

Yeah, PATH.S needs a bit of tidying up.

**Comment by bobbimanners** [comment]
Yeah I thought it was super weird!  It doesn't matter the order in the table.  It shows up in `*HELP` but that specific name it doesn't like!!  Thought I must be doing something embarassingly stupid.

**Comment by bobbimanners** [comment]
`CLILOOKUP` bug fixed.  `*TITLE` is done.
