### ISSUE TITLE
Implement `*REMOVE`

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#217]
`*REMOVE` is like `*DELETE` (deletes a single file) ... except there is no error message if file does not exist.

I missed this one when going through the ADFS manual originally.

**Comment by jgharston** [comment]
Simple enough, I'll add it to the FILE commands, it's just OSFILE with A=6, same as DELETE, but without checking the return state.

**Comment by bobbimanners** [comment]
I wasn't 100% sure if it was FILE or HOSTFS, so thanks for that!

**Comment by bobbimanners** [comment]
JGH implemented this.  Seems to work :)
