### ISSUE TITLE
`*LOAD` / `*SAVE` / `*RUN` loose ends

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#22]
`LOADFILE` needs code to use the file's aux address when `*LOAD file` is used without an address being passed.

`*SAVE` only handles start and end addresses, no entry point and relocate address.  I also do not support the START+LENGTH style of argument.  This could be improved!

`*RUN` needs to be implemented!  Just a stub for now.

All these commands need to accept optional quote marks.  Forth `CREATE-SCREENS` uses `*SAVE"filename" SSSS EEEE` to save screens.

In general handling entry point != start address is a pain in the neck because ProDOS only has one suitable address field (aux type) which is used for the load address.  Where could we store the start address?  Is this used often enough to be worth bothering with?

**Comment by jgharston** [comment]
*SAVE needs to handle exec addresses, it's OSFILE that decides what to do with them, not *SAVE.

I've been looking at the SAVEFILE code, but it's something I've been deferring until tidying the Kernel code. There's a method I use on the Spectrum host to store larger address data into a "smaller" field, I'll have a ponder. The simplest would be for OSFILE to just ignore exec addresses entirely, especially as BASIC's SAVE specifies an exec different to the load, so you can't just error if they are different.

**Comment by bobbimanners** [comment]
I have implemented a couple of pieces of this.

1) `*LOAD` with no start address specified now uses the aux type of the file as the start address.
2) `*RUN` is implemented.  However I don't think the `JMP (...)` at the end is working.  Address seems to be getting written to `AUXBLK`/`AUXBLK+1` as expected, so not sure why this is not working.

**Comment by bobbimanners** [comment]
`*LOAD` now uses the aux filetype as the start address if the user does not provide one.

`*RUN` is almost working.  It works like `*LOAD file` with no address (ie: loads it to the address given in the aux filetype.)  This address is copied to auxmem correctly but for whatever reason jumping to it is not working as expected right now.  It is late, and most likely something silly.

**Comment by jgharston** [comment]
On 19-08-2021 04:54, Bobbi Webber-Manners wrote:
> *RUN is almost working. It works like *LOAD file with no address (ie:
> loads it to the address given in the aux filetype.) This address is
> copied to auxmem correctly but for whatever reason jumping to it is
> not working as expected right now. It is late, and most likely
> something silly.

I'll have a look later. I was so shattered when I got home last night
I just went straight to bed - just after documenting two bugs in
chario.s so I didn't forget. ;)

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by jgharston** [comment]
On 18-08-2021 04:51, Bobbi Webber-Manners wrote:
>  	* *RUN is implemented. However I don't think the JMP (...) at the
> end is working. Address seems to be getting written to AUXBLK/AUXBLK+1
> as expected, so not sure why this is not working.

Possibly:

FSCRUN      STX   OSFILECB            ; Pointer to filename
             STY   OSFILECB+1
             LDA   #$FF                ; OSFILE load flag
             STA   OSFILECB+6          ; Use file's address
             LDX   #<OSFILECB          ; Pointer to control block
             LDY   #>OSFILECB
             JSR   OSFILE
* Ensure OSFILE &FF returns the control block filled in correctly:
* !(XY+2)=auxaddr
* !(XY+6)=auxaddr
* !(XY+10)=size
* ?(XY+14)=converted access byte
* ?(XY+15), ?(XY+16) = converted modification date
*
* Then, you should be able to do:
* JMP (OSCTRL+6) ; Jump to entry address

*        JMP  (AUXBLK)   ; DOESN'T WORK AS EXPECTED!!!
             RTS

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
Will take another look at this later.

**Comment by jgharston** [comment]
On 19-08-2021 14:20, Bobbi Webber-Manners wrote:
> Will take another look at this later.

Ah ha! Found out why *RUN isn't working. OSFILE isn't updating the
control block. Eg:

> *LOAD BASIC2.ROM
FILE A=FF Y=02 X=EE 00000000 000000FF 00000000 00000000 BASIC2.ROM
  CC  A=01 Y=02 X=EE 00000000 000000FF 00000000 00000000
control block not updated ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

BASIC2.ROM is &4000 bytes long and auxtype=&8000, so it should be
returning:
  CC  A=01 Y=02 X=EE 00008000 00008000 00004000 00xxxxC3
.....................whatever the date is --------^

Then FSCRUN can do JMP (FILECB+6)

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
My `*RUN` code is not yet using that control block though.  That was the next step once I got this existing `JMP (AUXBLK)` thing to work.

**Comment by bobbimanners** [comment]
Control block is now updated.  It is done in three steps:
- Mainmem code (`LOADFILE` and `SAVEFILE`) updates its local copy `FILEBLK` (which was copied from the OSFILE CB before entering main memory.)
-Mainmem code copies the control block to `AUXBLK` in aux (since we don't know the final address to copy to.)
- Upon return to aux mem, the code copies the control block from `AUXBLK` to the control block pointed to by XY on entry.
Seems to work.

**Comment by bobbimanners** [comment]
`*RUN` works now.

**Comment by bobbimanners** [comment]
Note - there are still some loose ends to deal with though.  Not all fields are updated for both LOAD and SAVE as they should be.

**Comment by bobbimanners** [comment]
The `OSFILE` control block is now updated for both LOAD and SAVE cases.  Closing this ticket.
