### ISSUE TITLE
Implement `VDU 19` palette changes

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#227]
`VDU 19,logical,physical,0,0,0` makes logical colour `logical` point to physical colour `physical` from the Applecorn 16-colour palette.

`VDU 19,logical,255,R,G,B` makes logical colour `logical` into a new custom colour determined by the 12 bit RGB values (4096 colours).

@jgharston Seems sensible?

**Comment by jgharston** [comment]
On 27-12-2022 02:16, Bobbi Webber-Manners wrote:
> VDU 19,logical,physical,0,0,0 makes logical colour logical point to
> physical colour physical from the Applecorn 16-colour palette.

Yep, in IBGR ordering, ie black,red,green,yellow,etc.... There's a
translation table in the VDU module, CLRTRANS16.

> VDU 19,logical,255,R,G,B makes logical colour logical into a new
> custom colour determined by the 12 bit RGB values (4096 colours).

The specification is
   VDU 19,logical,16,R,G,B makes logical colour logical into a new
   custom colour determined by R, G, B, using the highest bits that
   the hardware implements. (ie if you have 3x2-bit colour it is
   %00xxxxxx, %01xxxxxx, %10xxxxxx, %11xxxxxx; if it is 3x4-bit
   colour it is %0000xxxx to %1111xxxx; etc.)

See:
   https://beebwiki.mdfs.net/VDU_19

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
Awesome.  That should work nicely then.

**Comment by bobbimanners** [comment]
I have implemented `VDU 19, logical, physical, 0, 0, 0` and `VDU 19, logical, 16, red, green, blue` and both are working in `MODE 0` and `MODE 1`.

I haven't implemented `VDU20` yet.  Need to add checks not to enter this code unless the system is a GS.

**Comment by bobbimanners** [comment]
Added check that machine is GS before calling SHR palette routines for `VDU19`.  Implemented `VDU20`.
