### ISSUE TITLE
Check for GS before allowing MODE 0 / 1

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#233]
Maybe on the //e these two modes can just map to MODE 2.

Entering these modes on a //e will crash because there is 65816 code.

**Comment by jgharston** [comment]
MODE 0 should drop back to MODE 3 (80-column text)
MODE 1 should drop back to MODE 6 (40-column text)

**Comment by bobbimanners** [comment]
Done.  (`VDU22`)
