### ISSUE TITLE
VDU driver - paged mode

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#241]
I have a feeling the infrastructure is in place for this.  Would be useful to finish it off.  @jgharston What do you think?

**Comment by jgharston** [comment]
On 31-12-2022 08:50, Bobbi Webber-Manners wrote:
> I have a feeling the infrastructure is in place for this. Would be
> useful to finish it off. @jgharston [1] What do you think?

I think so. I'd been pondering how to "press SHIFT" on a machine
where you can't detect the SHIFT key, and I think the best option
is the same with using the digits as function keys, use the Apple
keys.

I'll update the BYTE76 routine to return the relevant info.

Functionally, what you do is:
VDU 14:
set FXLINES to 0
set vdu14 bit in VDUSTATUS

VDU 15:
set FXLINES to 0
clear vdu14 bit in VDUSTATUS

VDU 11 (and moving back from column 0):
DEC FXLINES
IF FXLINES<0, set FXLINES=0

VDU 10 (and moving forward from column max):
if vdu14 bit in VDUSTATUS is zero, skip past
if VPOS-bottom line, skip past
INC FXLINES
if FXLINES<bottom line, skip past
set FXLINES=0
loop:
CALL BYTE76, if SHIFT=0 go back to loop

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
I agree that using the Apple keys in lieu of shift is the way to go with this.  Thanks Jonathan :)

**Comment by jgharston** [comment]
OSBYTE76 now implemented, so can be called by VDU driver.

**Comment by bobbimanners** [comment]
Started to work on this then realized we are out of space in aux LC.  Need to work on moving a couple of routines to main mem first.
