### ISSUE TITLE
Copy cursor drawn in current text colour (`MODE 0` & `MODE 1`)

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#243]
If one uses the `COLOUR` statement to create a screen where there are several different colours of text, and then use the arrow keys to move the copy cursor over this text, the effect is seen.  The copy cursor is shown in the current text foreground / background colours, rather than the foreground / background colours at its current position.

Fixing this looks to be a nuisance - we would surely need to store the FG and BG colours for each text position on the screen.  How does the actual Beeb MOS handle this, I wonder.

**Comment by bobbimanners** [comment]
I think the answer to this is that the Beeb's copy cursor only occupies a single row of pixels 'between' characters (and it is always white).  Maybe we can do it the same way.  The key is not having to redraw the character that was covered by the cursor.

**Comment by bobbimanners** [comment]
I believe one possible solution is to modify `RDCHHND` in `auxmem.chario.s` ..
Line 161 `STA OLDCHAR` - here is where the old character is preserved
Line 173 `LDA OLDCHAR` - beginning of sequence where old char may be restored
We can add calls here to a routine which stores the 16 bytes (`MODE 0`) or 32 bytes (`MODE 1`) of screen memory and restores it.

**Comment by bobbimanners** [comment]
@jgharston I have looked at the code enough now to convince myself I need your assistance :) 

One tricky thing here is all the different types of screen (text, HGR, SHR) are manipulated by means of `PUTCHRC` which makes it hard to do something differently for SHR than for the others (especially as this is 'fast path' code where we care about performance.)

The existing copy cursor code looks quite delicate and I am a bit scared that I will break it in unexpected ways if I tinker with it.

Proposed plan:
1. We agree on a general strategy.  Whether it is saving the 16 or 32 bytes per char in SHR mode and restoring them afterwards, or we simply avoid erasing the pixels and just XOR a cursor in for SHR mode.  I prefer the second approach I think, since it is a little more elegant.  However that means we need to make `PUTCHRC` do different things to the text mode vs SHR, both of which are being maintained in parallel of course.
2. I will write whatever SHR routines we need in `auxmem.shr.s`
3. You implement the hooks in `auxmem.chario.s` to call the new SHR routines.

Anyhow, a penny for your thoughts :)

**Comment by jgharston** [comment]
On 03-01-2023 01:04, Bobbi Webber-Manners wrote:
> Proposed plan:
>  	* We agree on a general strategy. Whether it is saving the 16 or 32
> bytes per char in SHR mode and restoring them afterwards, or we simply
> avoid erasing the pixels and just XOR a cursor in for SHR mode.

I agree, XORing when in a graphics is the better option. It should 
"just"
need a BIT modeflags:Bxx textcursor/graphcursor at the start of the
existing routines.

>  	* I will write whatever SHR routines we need in auxmem.shr.s
>  	* You implement the hooks in auxmem.chario.s to call the new SHR
> routines.

Looks good. I haven't looked at the VDU code for some months. :)

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
I am about to do some refactoring so that the cursor drawing no longer affects my new VDU5 stuff (in `MODE 1` only at the moment, if you want to play with it.)  This will also help us move forwards on this issue too.

**Comment by jgharston** [comment]
On 09-01-2023 02:34, Bobbi Webber-Manners wrote:
> I am about to do some refactoring so that the cursor drawing no longer
> affects my new VDU5 stuff

In VDU 5 mode there is no visible cursor, so it should be a simple case
of test (VDUSTATUS bit):BNE skip_cursor_code

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
Will play with this tonight and see what works out best.

**Comment by bobbimanners** [comment]
Right now there are no cursors in SHR, but plan to put them back using XOR.

**Comment by bobbimanners** [comment]
We now have an XOR cursor.  Still working out the corner cases, but this bug is fixed.
