### ISSUE TITLE
It's about time we had version numbers

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#245]
Dates are all very well, but time to switch to version numbers.

I would like a way to ensure the minor version number gets incremented automatically somehow.

**Comment by xotmatrix** [comment]
Total Replay's Makefile uses the number of commits in the repo to generate a build number automatically.

**Comment by bobbimanners** [comment]
Sounds like a good idea :)

**Comment by bobbimanners** [comment]
Implemented a pre-commit hook to automatically generate a version number from the current tag plus the git tag (from `git describe`).  This is used to generate a file `auxmem.vers.s` which is incorporated into the build.

The version has the format `<tag>-1-gxxxxx` where the xxxxxx identifies the Git hash.

`<tag` is initially v0.50-beta, so the current version appears as Applecorn v0.50-beta-1-g15235d8.

The tag should be manually managed to bump up the version number 0.50->0.51->0.52 as desired.
