### ISSUE TITLE
Page2 80 column mode doesn't work on GS ROM01

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#25]
Screen is garbled, on my ROM1 GS anyhow.

**Comment by bobbimanners** [comment]
Confirmed problem.  The Alternate Text Mode CDA does not fix it alas.

I will need to implement 65816 code to support this, writing directly to banks E0 and E1 with shadowing disabled.

**Comment by bobbimanners** [comment]
Confirmed to work on ROM3, but not on ROM1.

**Comment by bobbimanners** [comment]
IRQ handling is borked on the GS.  See separate ticket.

**Comment by bobbimanners** [comment]
MODE 1 (40 cols) works on ROM1 GS with Alternate Text Mode CDA.  Would be nice to make MODE 0 work too, but this will require code to write to banks E0 and E1 directly as noted above.

**Comment by jgharston** [comment]
Works now!

**Comment by bobbimanners** [comment]
woohoo!

**Comment by bobbimanners** [comment]
Not working for me (yet) on ROM01 GS.

**Comment by jgharston** [comment]
On 25-09-2021 21:02, Bobbi Webber-Manners wrote:
> Not working for me (yet) on ROM01 GS.

I'll clone the current repo today and build up again on that.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
If you want to try to work from the version I merged, you can:
`git  checkout 7a4b65960e2436933b0bab3f3cfba74d0cac699d`

**Comment by jgharston** [comment]
On 25-09-2021 21:02, Bobbi Webber-Manners wrote:
> Not working for me (yet) on ROM01 GS.

That's "correct" functionality at the mo. ;) All the 65816
"bypass" code has been disabled, so it "correctly" doesn't
access the screen properly.

One of my emulators "correctly" emulates the ROM01 GS, but I
can't work out which it is, it could be the one on the
computer at work ;)  I'll test that tomorrow over lunch.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
I think if we also write to banks E0 and E1 as well as 00/01 (aka main and aux) then it is quite simple.  I had the E0 and E1 writes working in the version I was tinkering with yesterday.

I don't think any of the emulators gets the GS quite right.  And the way Applecorn works (running in aux memory, doing PAGE2 80 cols) is quite unusual and has triggered quite a few emulator bugs.  Probably the latest MAME 0.234 is the best emulation, but I know even it has bugs still.

I am just getting Applecorn building in Merlin-16 again and then I will do some playing on the GS.

**Comment by jgharston** [comment]
On 26-09-2021 23:21, Bobbi Webber-Manners wrote:
> I am just getting Applecorn building in Merlin-16 again and then I
> will do some playing on the GS.

What on earth am I doing that breaks the Merlin-16 build process????

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
Either Merlin-16 hates whitespace in some of the initializers:
```
FOO DB 1,  1,  0
```
or the tool I used to import to Merlin format (Cadius) is messing it up.

Not sure which.

```
FOO DB 1,1,0
```
is fine.

**Comment by bobbimanners** [comment]
Fixed!!
