### ISSUE TITLE
Function keys not working in View / ISO Pascal Editor

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#265]
Just noticed this problem.

In View the function keys are still working as softkeys.  I can do `*KEY 1 FOO` and then in the editor, F1 will print 'FOO'.  So we know the keys are being detected, but somehow they are acting as softkeys when they should be just generating keycodes to control View functions.  This is a regression.

@jgharston Any ideas?

**Comment by jgharston** [comment]
On 14-01-2023 01:46, Bobbi Webber-Manners wrote:
> In View the function keys are still working as softkeys. I can do *KEY
> 1 FOO and then in the editor, F1 will print 'FOO'. So we know the keys
> are being detected, but somehow they are acting as softkeys when they
> should be just generating keycodes to control View functions. This is
> a regression.
> 
> @jgharston [1] Any ideas?

Odd, it was working when I last checked about a week or so ago. I'll
have a look at it.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by jgharston** [comment]
Ah, I've seen the problem, there's a line swapped for some debugging
left in. I'll fix it when I get home this evening.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh
