### ISSUE TITLE
MODE 1 Copy editor bug with line >40 columns at bottom of screen

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#38]
If you have a line longer than 40 characters and you are in MODE 1  at the bottom of the screen and you copy the line, the wrong stuff will get copied once you reach the end of the line (and the screen scrolls)

**Comment by jgharston** [comment]
That needs the VDU driver updated to action the "do not scroll" flag in VDUSTATUS. Copy editing sets it, the VDU driver doesn't yet action it.
The same bug should be visible in MODE 0 with a 80-character line at the bottom of the screen.

**Comment by jgharston** [comment]
Should be fixed now with KBD driver bugfixes.

**Comment by bobbimanners** [comment]
Seems to be fixed to me too :)  Closing this ticket.
