### ISSUE TITLE
LISP does not work

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#4]
REPL runs but nothing gets evaluated and printed.  Some attempt at a backtrace.

**Comment by bobbimanners** [comment]
Implemented code for passing unknown OSCLI strings to the service entry point of the ROM.  This allows Cold Restart to proceed. 

LISP still seems to think there is always an escape condition though, so nothing gets evaluated or printed.

**Comment by jgharston** [comment]
Yeah, I'm going to try single-stepping through the code to see what's happening.

**Comment by bobbimanners** [comment]
Let me know what you find out.  Very curious about this one!

**Comment by bobbimanners** [comment]
Comment from A2Infinitum Slack (Iván Izaguirre)
"I looked at the issue with Lisp on Applecorn. It may be the implementation of OSWORD05 lacking an extra indirection. It returns the value at xy, instead of using that as the address of the 32 bit structure that has the address requested. The address requested happens to be 0xff. I haven't been able to verify and I may be wrong or if that is enough to have Lisp running."

**Comment by jgharston** [comment]
I spotted that, it's doing LDA (OSCTRL),0 : STA (OSCTRL),4 so fetching from the control block instead of fetching from the address in the control block. I've got the fix for that, but I'm waiting for Bobbi to shuffle the code around into functional VDU/ FileSys/ Kernel sections.
I'm at work, so I can't post the code ;)

**Comment by bobbimanners** [comment]
I did some shuffling around.  The VDU stuff is all in one spot now.

(I did try a more radical cleanup, but that broke stuff in mysterious ways, so I decided to go the gradual route.)

**Comment by jgharston** [comment]
Quick fix:
OSWORD5     LDA   (OSCTRL)
            STA   OSINTWS
            LDY   #$01
            LDA   (OSCTRL),Y
            STA   OSINTWS+1
            LDA   (OSINTWS)
            LDY   #$04
            STA   (OSCTRL),Y
            RTS

**Comment by bobbimanners** [comment]
Didn't spot your comment and did my own fix.

Lisp seems happier now.  There is still some remaining issue which appears to be a quirk when parsing keyboard input in Lisp.
