### ISSUE TITLE
Forth `CREATE-SCREENS` word only creates first file

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#41]
This command does something like: `*SAVE"0SCREEN" SSSS EEEE` and repeats 10 times.

I already hacked the Host FS code to add a letter  'N' in front of leading digits (so `0SCREEN` -> `N0SCREEN`) and now the first file gets created.  But the subsequent calls seem to fail with a beep error.

**Comment by bobbimanners** [comment]
The new OSCLI handler does not like the strings that Forth sends it!

**Comment by jgharston** [comment]
Now GSTRANS is written, this could probably be fixed once HostFS uses GSTRANS to read the filename.

**Comment by bobbimanners** [comment]
One other thing that needs to be handled better is filename beginning with a digit.  Forth tries to create `0SCREEN`, `1SCREEN` etc.  I think I bodged it in `SAVEFILE` for now (to add an `N` in front, since ProDOS does not allow initial digits in filenames.)  But this maybe ought to be done by `PREPATH` ...

**Comment by jgharston** [comment]
On 02-09-2021 20:20, Bobbi Webber-Manners wrote:
> One other thing that needs to be handled better is filename beginning
> with a digit. Forth tries to create 0SCREEN, 1SCREEN etc. I think I
> bodged it in SAVEFILE for now (to add an N in front, since ProDOS does
> not allow initial digits in filenames.) But this maybe ought to be
> done by PREPATH ...

Yes, doing it in PREPATH would be neater. HostFS passes the raw filename 
over, PREPATH sorts out the localisation.

I've noticed CiderPress puts a leading N on filenames with a leading 
digit, so I assume this is a standard munging method.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
I didn't know Ciderpress did that, but great minds think alike ;)

**Comment by bobbimanners** [comment]
Raised ticket #60 related to this.

**Comment by bobbimanners** [comment]
Works now!!
