### ISSUE TITLE
Option to start in 40 cols (`MODE 1`)

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#46]
Since 80 cols page two seems really broken with Fastchip //e accelerator.

**Comment by jgharston** [comment]
Already added this. init.s calls INITKBD before INITVDU so that INITKBD can return the startup screen mode. Once the VDU driver is next updated, VDUINIT will action this. Currently, KBDINIT returns MODE 0, but VDUINIT ignores it at the mo, but it's all set up and ready.

**Comment by jgharston** [comment]
INITKBD returns a 'startup byte' similar to the BBC MOS, This include the startup screen MODE to pass on to VDUINIT. You should be able to test by pressing a digit key when you press Ctrl-Break. Does this work? It doesn't on an emulator because the multiple keypresses clash.
Eg, Ctrl-1-Break should start up in 40-col MODE 1.

**Comment by bobbimanners** [comment]
Yes that does work on my real //e :)

**Comment by bobbimanners** [comment]
It may be worth adding a check for 'any key down' (which I think the //e can do.)  Otherwise you get a pile of digits on autorepeat after the reset has completed.

**Comment by bobbimanners** [comment]
High-bit when you read the keyboard strobe ($C010) is "any key down" flag.  I will play with it at some point once I am done fighting with wildcards.

**Comment by jgharston** [comment]
On 10-09-2021 16:56, Bobbi Webber-Manners wrote:
> High-bit when you read the keyboard strobe ($C010) is "any key down"
> flag. I will play with it at some point once I am done fighting with
> wildcards.

Yes, I put a "is any key pressed" code in the keyboard driver ages ago
(three weeks? seems like ages). So, if a key is pressed it should be
read and acknowledged:

              LDX   #$C0
              STX   FX254VAR       ; b7-b4=default KBD map, b3-b0=default 
MODE
              BIT   SETV           ; SETV to test for keypress
              JSR   KBDTEST
              BCS   :KBDINITOK     ; Return default MODE=0
              STA   $C010          ; Ack. keypress
              TAX                  ; Use keypress as default MODE
:KBDINITOK   TXA
              RTS


KBDREAD      CLV                  ; VC=return keypress
KBDTEST      LDA   $C000          ; VS here to test for keypress
              EOR   #$80           ; Toggle bit 7
              CMP   #$80
              BCS   KBDDONE        ; No key pressed
              BVS   KBDDONE        ; VS=test for keypress
...
KBDDONE      RTS

So, pressing Ctrl-1-Break should start in MODE 1..... unless the 
keyboard
hardware supresses keypresses for Ctrl+Number.  Hmmm. Try Ctrl-A-Break.


-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by jgharston** [comment]
On 10-09-2021 15:48, Bobbi Webber-Manners wrote:
> Yes that does work on my real //e :)

Yeyyy!!!!


-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
Hold the appropriate number key while Applecorn is loading the ROM file to set the startup mode.  Added a comment to `README.md` so closing this.
