### ISSUE TITLE
`*DIR` enhancements

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#47]
Right now it sets the prefix to the empty string which is not too useful.

It could go to the top level of the currently logged volume or something?

**Comment by jgharston** [comment]
On a "dir/file.ext" file system, as on the Apple:
*DIR /
should select the root directory.
*DIR <nothing>
should select the home directory logged into with something such as *I AM username. It could be argued that the "home directory" on a non-networked system is the root directory.

**Comment by bobbimanners** [comment]
As a start, `*DIR ^` will take you to the parent dir.  This will be improved over time to allow more complex usages like `*DIR ^/SOMEWHERE`, or even `^/^/SOMEWHERE/ELSE`

**Comment by bobbimanners** [comment]
We need a way to select drives by slot and drive number in case we do not know the volume dir name.

Maybe the `*DRIVE` command is a good fit for this.  `*DRIVE 61` would select slot 6, drive 1 and set the prefix to whatever volume is present there.

**Comment by bobbimanners** [comment]
Done.  See `README.md` for details of what has been implemented.
