### ISSUE TITLE
Need no-op `OSBYTE` $0B, $0C, $0F for Forth

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#62]
Otherwise `VLIST` output is very messy ;)

**Comment by bobbimanners** [comment]
Maybe we just need a list of OSBYTEs which are no-ops and just do not emit the annoying message?

I don't want to turn the annoying message off completely because it is useful when debugging ROMs that don't work and for determining if there are any additional calls we ought to be supporting.

**Comment by jgharston** [comment]
The updated bytwrd.s should get rid of them, they're added in as BYTENULLs along with adding in the entries for BYTE75 and BYTEA0.
I think I might implement a dummy *OPT call to turn debug messages ON/OFF.
Ooo, time for bed! :)

**Comment by bobbimanners** [comment]
Fixed in latest & greated.  Need no-op OSBYTE $0F too (also FORTH `VLIST`).

**Comment by bobbimanners** [comment]
Added no-op OSBYTEs 13, 14, 15 (ie: up to $0F).
