### ISSUE TITLE
Need ||gs detection - also ROM1 vs ROM3

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#66]
JGH code for 65816 detection is checked in.  Need specific GS detection too.  Would be nice if we can detect ROM1 vs ROM3 since only ROM1 needs a workaround for PAGE2 80 col.

**Comment by Dekkion42** [comment]
Perhaps this will help:
Machine Identification Information: 
https://prodos8.com/docs/technote/misc07/
https://prodos8.com/docs/technote/misc02/

I cannot locate how to tell Rom1 vs Rom3, I know I have seen the code somewhere (Granted maybe I was dreaming)

**Comment by bobbimanners** [comment]
Thank you :)

**Comment by bobbimanners** [comment]
https://github.com/a2-4am/4cade/blob/master/src/4cade.init.a#L58

**Comment by bobbimanners** [comment]
4am says: "Need to check 8-bit machine ID byte first" (or bad stuff happens ;) )

**Comment by bobbimanners** [comment]
This has been addressed now.
