### ISSUE TITLE
Implement wildcards

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#69]
ADFS uses `*` and `#` (matches single character) as wildcard chars.

As far as I can tell, the following commands accept wildcards but ony handle a single file:
`CAT`, `DIR`, `EX`, `EXEC`, `LOAD`, `RUN`

and the following commands work on multiple files using wildcards:
`COPY`, `DESTROY`, `INFO`.

I propose to do something similar.

**Comment by bobbimanners** [comment]
Oh and it implements wildcards anywhere along the path, so things like `/AAA*/BBB*/CC*.TXT` ought to work (if unique.)

No idea how it behaves when things are not unique (use first match or error?)

**Comment by bobbimanners** [comment]
Answer to Q above is: if not unique, just use first match.

**Comment by bobbimanners** [comment]
Implemented wildcard code (new file `MAINMEM.WILD.S`.  Using it for `*DIR` only at present.

**Comment by bobbimanners** [comment]
I wonder if ADFS is smart about whether it is looking for a file or directory.  If I do *DIR /H1/A* for example, we know the A* is looking for a dir.  Right now it just does first match regardless, but I am wondering if it ought to be first matching DIR or first matching (non-dir) FILE according to context.  Maybe @jgharston knows the answer?

**Comment by bobbimanners** [comment]
Also worth noting here.  I don't have code yet to support match first / match next type semantics required for the commands that can operate on multiple files.  (ie: <listspec>, in ADFS terms.)

**Comment by jgharston** [comment]
On 09-09-2021 19:52, Bobbi Webber-Manners wrote:
> I wonder if ADFS is smart about whether it is looking for a file or
> directory. If I do *DIR /H1/A* for example, we know the A* is looking
> for a dir.

No it isn't, it matches the first object regardless of object type.
Eg:
PATTERN WR
PROGS DL
PROGVERS WR

LOAD "P*" will match PATTERN
*DIR P* will match PATTERN and generate 'Not a dir.'
LOAD "PR*" will match PROGS and generate 'Not a file'
*DIR PR* will match PROGS

I don't know of any filing systems for Acorn kit that passes
the object type as well as the wildcard name to the wildcard
matching code.

I know the SJ MDFS file server is clever enough to do multiple
wildcarded renames, so it could do object matched wildcard
matching, I'll check later.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
OK that makes it easier, since that is what the code does today.

I think the error handling needs some tweaking to give 'Not a dir' / 'Not a file'.  It is confusing otherwise!  Maybe you could help me get that right?

My secondary school Acorn experience was BBC B's with an SJ Research Econet server.

**Comment by jgharston** [comment]
On 09-09-2021 21:05, Bobbi Webber-Manners wrote:
> I think the error handling needs some tweaking to give 'Not a dir' /
> 'Not a file'. It is confusing otherwise! Maybe you could help me get
> that right?

I'l have a look tomorrow, we only have on client booked in all day. :)

> My secondary school Acorn experience was BBC B's with an SJ Research
> Econet server.

You're blessed, they are the best file servers ever produced. I've had
one since 1998 after ten years of lusting after one, it has almost all
my BBC development code on it.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
I remember it had a 20MB drive and all the kids got a 50KB quota.  You  could get double if you had a good excuse!  It also had an Epson FX80 for shared printing.  Was pretty neat for the time!

**Comment by bobbimanners** [comment]
@jgharston 
Am I right to assume `OSFIND` will support wildcards for read or modify but not for write? Right now it does wildcards in all cases.

**Comment by bobbimanners** [comment]
Implemented multi-file handling for `*ACCESS`.  It works but there are some known bugs:
- For some reason `????` does not match the `BCPL` directory, but `B???` or `B??L` does.
- `*ACCESS *.ROM L` works, but `*ACCESS * L` does not.

**Comment by jgharston** [comment]
On 09-09-2021 21:19, Bobbi Webber-Manners wrote:
> @jgharston [1]
> Am I right to assume OSFIND will support wildcards for read or modify
> but not for write? Right now it does wildcards in all cases.

OPENIN("wild*card") is fine
OPENUP("wild*card") is fine
OPENOUT("wild*card") should generate a "Wildcard" error as it's creating 
a new file.

save as SAVE "wild*card"

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
After some testing discovered that wildcards seem to be working properly in subdirectories but there are some oddities in the volume directory.  Should be easy to track down.

**Comment by bobbimanners** [comment]
Fixed the known wildcard bugs.  When a wildcard search was resumed (ie: "find next") it was failing to load the next directory block and was reading off the end of the buffer.  Fixed now (although the code is a bit ugly.)

**Comment by jgharston** [comment]
On 10-09-2021 19:39, Bobbi Webber-Manners wrote:
> Fixed the known wildcard bugs. When a wildcard search was resumed (ie:
> "find next") it was failing to load the next directory block and was
> reading off the end of the buffer. Fixed now (although the code is a
> bit ugly.)

First rule of code: get it working first, optimise later. ;)

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
"Premature optimization is the root of all evil"

**Comment by bobbimanners** [comment]
I just checked in two commits: one to support '#' as well as '?', and the other to not evaluate wildcards for OSFIND with access type "w".

**Comment by bobbimanners** [comment]
Everything in this thread is addressed.  Will open new ticket for the error handling and close this.
