### ISSUE TITLE
Separate repo for Manuals

### ISSUE THREAD

**Issue by jgharston** [bobbimanners/Applecorn#70]
Suggest the Manuals directory be a separate repository, currently you have to download the full 90M to clone the repo when the source code you're cloning is only a couple of meg.

**Comment by bobbimanners** [comment]
Yeah, good idea!

**Comment by bobbimanners** [comment]
I may shove these on my dev website (bobbi.epizy.com) when I update it to add Applecorn.  Then we can just link to them from Github.

**Comment by jgharston** [comment]
Any progress on this? It's a bit of a bind downloading 300M+ when just needing 1M of code files. ;)

**Comment by bobbimanners** [comment]
I wonder how much space I have in my free webspace.  If it is enough for the manuals, I will move them there and remove from Github.  Other option I suppose is to shove them in a separate Github repo (when all you have is a hammer, everything looks like a nail!)

**Comment by bobbimanners** [comment]
I ended up putting them in a separate repo 'Applecorn-Manuals'.

My free webspace has a file size limit that a couple of the manuals exceed.

**Comment by bobbimanners** [comment]
@jgharston I did some funky stuff with BFG Repo-Cleaner (https://rtyley.github.io/bfg-repo-cleaner/) to completely remove the PDFs from the Git history.  PLEASE DELETE ANY LOCAL CLONES AND RECHECK OUT (otherwise they may come back!)
