### ISSUE TITLE
MicroProlog does something weird with OSCLI calls

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#72]
I am having troubling calling OS commands with args from Microprolog.  Maybe I need to read the manual, or maybe it does something a bit odd when it calls OSCLI.

**Comment by bobbimanners** [comment]
Oh, and I have to double up the star for some reason, so `**CAT` works, for example.  But `**CAT SOMEDIR` does not.

**Comment by jgharston** [comment]
I think I'll add a *OPT255 debug display for OSCLI calls, then we can see what it's (trying) to do.

**Comment by bobbimanners** [comment]
Good plan :)

**Comment by bobbimanners** [comment]
Page 154 of the MicroProlog manual suggests it is correct.  `**` is required and I believe quotes around the whole thing if has whitespace, so `**CAT MYDIR`.

**Comment by bobbimanners** [comment]
`**"."` works.  Closing this.
