### ISSUE TITLE
Crashes with Copy Cursor with Sep 9 VDU update

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#73]
Could have been a bug I introduced, but I am getting crashes trying to copy text with the cursor keys and tab (specifically, on pressing Tab.)

**Comment by jgharston** [comment]
I'll investigate.

**Comment by jgharston** [comment]
Fixed. The CHARIO code was making a fast call to the internals of the VDU driver, but that became a fast call for cursor movement - COPY needed to enter at the printable character entry.

**Comment by bobbimanners** [comment]
Confirmed fixed.
