### ISSUE TITLE
Implement `*INFO`

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#76]
`*INFO` prints the same info as `*EX`, but accepts a list of files using wildcards rather than a single directory.

**Comment by bobbimanners** [comment]
@jgharston I could use your thoughts on this one.  As I understand it `*INFO` is like `*EX` but takes an <obj-list> so `*INFO *.TXT` would do what one would expect.  Right now the handling for `*INFO` winds up in the same places as that for `*CAT`/`*EX` which is all done in aux memory.  However, my  wildcard stuff is in main memory (as needed for `*COPY`,`*DESTROY` etc.)  Makes me wonder if we should move all the catalog stuff to main memory and have a way for main memory code to 'print' on the Beeb console, through the VDU driver (service call in reverse.)  This also sounds pretty painful to do and requires reworking code that already works, so I am open to better suggestions.  Am I missing something?

**Comment by bobbimanners** [comment]
Or, even crazier idea, code in mainmem does the wildcard stuff and returns a hand-crafted directory block to auxmem which only has the matching entries.  That is actually less disruptive.

**Comment by bobbimanners** [comment]
Ah yeah, it is easy!!  I just set the deleted status on any that don't match and the code in auxmem already knows how to skip them.  Sorry, thinking out loud here.

**Comment by jgharston** [comment]
:)

**Comment by bobbimanners** [comment]
I nearly have this working once I squash a couple of pesky bugs.

**Comment by bobbimanners** [comment]
Finally have the fscking thing implemented and checked in before it breaks again ;)

There is a spurious 'I/O Error' at the end, will deal with that in due course.
