### ISSUE TITLE
Error handling for wildcards

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#77]
We need 'Not a dir' and `Not a file' type errorcodes.  Right now some of them are plain wrong.

**Comment by bobbimanners** [comment]
Also see the `TODO` comments in the code.

**Comment by bobbimanners** [comment]
@jgharston I could use some help getting all the error codes correct!

**Comment by jgharston** [comment]
On 16-09-2021 04:22, Bobbi Webber-Manners wrote:
> @jgharston [1] I could use some help getting all the error codes
> correct!

I'll have a look through them at the weekend.


-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
@jgharston Did you get a chance to look at this perchance?

**Comment by jgharston** [comment]
I'm working on this today. Wanted to get my VDU notes typed up and tested before digging in.

**Comment by bobbimanners** [comment]
Thanks!  Just FYI I am travelling on a work trip this week (first time in two years!)  I may be a bit slower than usual merging stuff!

**Comment by jgharston** [comment]
On 03-10-2021 15:43, Bobbi Webber-Manners wrote:
> Thanks! Just FYI I am travelling on a work trip this week (first time
> in two years!) I may be a bit slower than usual merging stuff!

My car has failed its annual test, so I'll be travelling to work on the
bus for the next week, so "need" something to occupy myself. :)

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
@jgharston How is SVC.S looking?  Incidentally, I am back home now :)

**Comment by bobbimanners** [comment]
@jgharston Is this all wrapped up now and I can close the ticket?  Seems like that may be the case :)

**Comment by bobbimanners** [comment]
In that case ... ticket closed!
