### ISSUE TITLE
Need `@` - to represent current directory

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#78]
ADFS uses `@` for this purpose.  eg: `*COPY FOO/BAR/*.TXT @`

**Comment by jgharston** [comment]
As it's a dir/file.ext filesystem, also "."
ie "./file.ext" is "file.ext" in the current directory, same as "@/file.ext"
just as "../file.ext" is the file in the parent directory.
Simple enough when '@' is an illegal character on ProDOS.

**Comment by jgharston** [comment]
Also, *COPY FOO/BAR DESTDIR where BAR is a directory should be identical to *COPY FOO/BAR/* DESTDIR
If (source is dir) THEN (dest must be a dir, copy everything in recursively)
If (source is file) THEN (if leaf has no wildcards) THEN (dest must be a file, copy single file)
If (source if file) THEN (if leaf has wildcards) THEN (dest must be a directory, copy matching files only to dest dir, nonrecursively)

You can get really funky if you want to implement postfix switches, *COPY src dest ~C~FW~TSPQ~V ;)

**Comment by bobbimanners** [comment]
Is it a fully recursive deep copy or a shallow copy of the contents of the top level dir?

**Comment by jgharston** [comment]
On 12-09-2021 03:41, Bobbi Webber-Manners wrote:
> Is it a fully recursive deep copy or a shallow copy of the contents of
> the top level dir?

RISC OS and some other systems implement switches to control recursion 
and
other stuff, but without that:

*COPY nowildsourcefile nowilddestfile
copies the single file, for example
*COPY fred/jim/sheila hazel/bob
copies the file sheila within the directory jim within the directory 
fred
within the current directory, to a new file or overwriting a file called
bob within a directory hazel (that must exist) within the current 
directory.

This is the only functionality that the stock ADFS and most other filing
system *COPY command implements. Extra functionality is usually 
implemented
by external programs such as TreeCopy and similar.

However, if you wish you could also implement:

*COPY sourcedir destdir
copies everything in sourcedir and everything in any subdirectories, 
into
destdir, creating destdir and any subdirs needed. For example
*COPY fred/jim hazel/bob
would create the directory bob if it doesn't exist, and copy all the 
objects
inside jim into bob, including any subdirectoties inside jim and their
contents, which would create subdirectories in bob.


*COPY wildsource destdir
copies multiple files to the destination directory, for example
*COPY fred/jim/s* hazel
copies everthing in the directory fred/jim that matches "s*" into the
directory hazel (which must exist)

This is where the issue of recursion/nonrecusion comes up. If "s*"
matches a directory, do you recurse into it? I would say no, you
are specifiying just the stuff in "fred/jim" that matches. So, if
fred/jim contained:

ARITH WR
BOB DL
SHEILA WR
SHERBERT DL
SHOOBERT WR

then "*COPY fred/jim/s* hazel" should copy SHEILA and SHOOBERT but not
SHERBERT and its contents.



-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
I am thinking to suport wildcards since it was a lot of work to implement them and we may as well use them.  Initially I will do a copy of just the mstching files (not dirs) like your last example.  According to the manual I have, this is consistent with what ADFS does.  We can add recursive 'treecopy' later.

**Comment by bobbimanners** [comment]
Implemented `@` and `.` to mean current working directory.
