### ISSUE TITLE
`*FREE` Misc. cosmetic stuff

### ISSUE THREAD

**Issue by jgharston** [bobbimanners/Applecorn#80]
*FREE should have optional drive parameter, so "*FREE" displays for current drive.
Display should be along the lines of:
HEXHEX Sectors = DECDECDEC bytes free
HEXHEX Sectors = DECDECDEC bytes used

HEXHEX zero padded (ie PRHEX and PR2HEX), and DECDECDEC space padded (ie PRDECXY).

eg:
>*FREE
000056 Blocks =   28672 bytes free
000224 Blocks =  114688 bytes free
>

Of course 140K is more than 65535, so PRDEC16 won't print it. I've put initial code in place to allow PRDEC to print wider numbers.

**Comment by bobbimanners** [comment]
ProDOS volumes can be up to 32MB, by the way.

**Comment by bobbimanners** [comment]
Also the decimal number printing code does not print 0 for value zero, but instead the empty string!  Or a number zero digits long ;)

**Comment by jgharston** [comment]
I've been getting 'File not found' occasionally from *FREE. Eg:

>*FREE :61
File not found
>_

I'm trying to work out what circumstatances reproduces it.

**Comment by bobbimanners** [comment]
I am trying to think how that could happen.  I will see if I can repro too.

**Comment by jgharston** [comment]
Can't reproduce, suggest we close.

**Comment by bobbimanners** [comment]
Then close it we shall.
