### ISSUE TITLE
Machine identification

### ISSUE THREAD

**Issue by jgharston** [bobbimanners/Applecorn#84]
In the updated CHARIO.S there's a bit of test code that's turned on with *OPT 255,64
Could you document on as many systems as possible what the results of the following is:

*OPT 255,64
A%=129:X%=-256:Y%=-1:PRINT ~USR&FFF4

(that's minus 256, minus 1)

Ta.

**Comment by bobbimanners** [comment]
Apple //e Enhanced with 65816 (Ultrawarp): `B0FFE081`.
Apple //e Enhanced using 1MHz 65C02: `B0002E81`.

**Comment by bobbimanners** [comment]
Apple IIGS ROM1: `B0002A81`

**Comment by bobbimanners** [comment]
Apple IIGS ROM3 (GSPlus emulator): `B0037F81`

**Comment by bobbimanners** [comment]
Hope that helps!

**Comment by jgharston** [comment]
On 17-09-2021 23:06, Bobbi Webber-Manners wrote:
> Apple //e Enhanced using 1MHz 65C02: B0002E81.
> Apple IIGS ROM1: B0002A81

I think those two you didn't do *OPT 255,64 first.
Or didn't use the chario.s with the test code in.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
Apple //e with Ultrawarp (65816): `B0FFE081`

**Comment by bobbimanners** [comment]
GS ROM1 : `B0017F81`

**Comment by bobbimanners** [comment]
Same results as before I think.  I am using today's snapshot (2021-09-21).  Perhaps the test code got dropped on the floor at some point?

**Comment by bobbimanners** [comment]
GS identification seems to work now.
