### ISSUE TITLE
Tidying memory swap macros

### ISSUE THREAD

**Issue by jgharston** [bobbimanners/Applecorn#87]
I've been looking at some of the macros in applecorn.s. Some could be tidied up a bit.

XF2MAIN and ENTAUX save and restore the contents of STRTL and STRTH. These are $03ED and $03EE in the "Acorn" side. We could declare those private to the memory swapping code and not save and restore them. That area of memory is not currently used, so we could declare it XFER workspace, getting rid of STRTBCKL and STRTBCKH.

**Comment by bobbimanners** [comment]
Sounds like a good plan.  The existing code which saves and restores thost locations is a bit ugly!

**Comment by bobbimanners** [comment]
Also, we may want to double check we have interrupts disabled everywhere we are messing with the memory softswitches.

The one quirk I am aware of at present is with the VidHD card (modern HDMI graphics card) in a IIgs.  We get some spurious characters in 80 column mode.  Strangely, any error (which invokes the BRK handler) seems to 'fix' the issue.

**Comment by bobbimanners** [comment]
I just checked in some improvements to the IRQ/BRK handler, so we shall see if it makes any difference.

**Comment by bobbimanners** [comment]
@jgharston Shall I close this one, or more to do?

**Comment by jgharston** [comment]
On 15-10-2021 00:14, Bobbi Webber-Manners wrote:
> @jgharston [1] Shall I close this one, or more to do?

I might tweek the macros going the other way, main to aux, leave it open
for the moment.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
Gonna close this.  See #157.
