### ISSUE TITLE
Bitmapped characters in `MODE 2`

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#89]
We should support text in the HGR bitmapped graphics `MODE 2`.

**Comment by jgharston** [comment]
Yes, 'cos I can't see anything! :D

**Comment by bobbimanners** [comment]
haha indeed :)

Here is a thought.  When we are in HGR `MODE 2` maybe we should also keep writing characters into 40 column `MODE 6` as well as doing the bitmapped font stuff.  That would make the copy cursor stuff much easier than having to pattern match the pixels.  It may also allow some other cheats.  And no memory is wasted.

What do you think?

**Comment by jgharston** [comment]
On 23-09-2021 02:39, Bobbi Webber-Manners wrote:
> Here is a thought. When we are in HGR MODE 2 maybe we should also keep
> writing characters into 40 column MODE 6 as well as doing the
> bitmapped font stuff. That would make the copy cursor stuff much
> easier than having to pattern match the pixels. It may also allow some
> other cheats. And no memory is wasted.

That would certainly make copy cursor stuff easier.
I've already put in stubs to branch to do bitmapped characters,
it's simple to tweek it so it's a branch after writing to the
character screen instead of instead of.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
Looks like this should be fairly straightforward.

**Comment by bobbimanners** [comment]
Characters are getting plotted to the HGR screen now.  No scrolling yet though.

**Comment by bobbimanners** [comment]
One bug at present ... if you go from `MODE 0` to `MODE 2` it thinks there are 80 chars per line.  Works okay if you go grom `MODE 1` to `MODE 2` though.

**Comment by bobbimanners** [comment]
@jgharston 
![Screenshot from 2021-09-23 18-00-48](https://user-images.githubusercontent.com/11758908/134591963-0a5fd0b7-8f3a-42ac-89f9-2c1f1dfc6ac4.png)

**Comment by bobbimanners** [comment]
Scrolling the HGR screen is now implemented.

`CLREOL` does not work on HGR yet though.

I am going to close this ticket and open a more specific one for the remaining loose ends.

**Comment by jgharston** [comment]
Last night I was getting successful at character output with ROM1
version AppleGS, but it still needs a bit of work because the code
then falls over on the non-GS Apples! But at least I know how to
do it.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
Excellent!!
