### ISSUE TITLE
Support for HGR graphics

### ISSUE THREAD

**Issue by bobbimanners** [bobbimanners/Applecorn#9]
Implement support for HGR graphics as a 'MODE'.  HGR is just in main memory so the buffer will not impinge on the "BBC World" running entirely in aux memory.  Can use the Apple II monitor ROM hi-res routines.

**Comment by jgharston** [comment]
In essence, the "BBC MOS"/"Apple" environment is just the Tube/Host environment, the aux memory is the language processor, the main memory with Apple monitor I/O is the host processor.

**Comment by bobbimanners** [comment]
Maybe use this: https://github.com/fadden/fdraw

Should be faster than the ROM routines (and will be way faster than the ROM when using the Ultrawarp.)

**Comment by bobbimanners** [comment]
Added FDraw library to the build.

Moved the ORG in main memory to $4000 to be clear of HGR page 1.

Verified FDraw initializes and clears HGR screen.

**Comment by bobbimanners** [comment]
- `MODE 2` now enables 280x190 HGR page 1 graphics.
- `CLG` is hooked up and works (VDU 16).
- `CCOL` has a hard-coded colour (VDU 18).
- `PLOT` plots a hard-coded line (VDU 25).
All seems to work.  Need to integrate properly with VDU driver.  @jgharston  :)

**Comment by bobbimanners** [comment]
Basic plotting is working - `PLOT 4,x,y` and `PLOT 5,x,y` (aka 'MOVE' and 'DRAW').

There is no scaling yet, I am using native 280x192 coordinates with origin top left.

**Comment by jgharston** [comment]
On 18-09-2021 03:39, Bobbi Webber-Manners wrote:
> All seems to work. Need to integrate properly with VDU driver.
> @jgharston [1] :)

Spent the weekend doing my taxes. ;)  That's out of the way for
another year now. :D

Just about to download the current repo and update my local copy.


-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
`HGR` is a bit of a work in progress.  `MODE 2` if you wanna try it out.  I am just putting in the scaling for 1280x1024 and it is slightly busted at the moment.  About to fix it!

**Comment by bobbimanners** [comment]
It is basically working, just don't try to draw off-screen!  (or it trashes memory ...)

**Comment by bobbimanners** [comment]
Some John Brooks magic.  This is way faster than my code:
```
  1 *-------------------------------
  2 * BBC2HGR - 1280x1024 -> 280x192
  3 *
  4 * By John Brooks - 9/19/2021
  5 *-------------------------------
  6 * Merlin 2.58 asm syntax
  7 *-------------------------------
  8 * For Bobbi's Applecorn project
  9 *-------------------------------
  10     lst  on
  11     xc        ;65c02 opcodes
  12     org  $2000
  13 
  14 VDUQ   equ  $280
  15 ZP1   equ  $60
  16 ZP2   equ  $62
  17 
  18     cyc  on
  19 BBC2HGR
  20 * X-coordinate in VDUQ+5,+6  1280*7/32=280
  21     ldx  VDUQ+5
  22     ldy  VDUQ+6
  23     lda  :XLoMul7Div32,x
  24     clc
  25     adc  :XHiMul7Div32,y
  26     sta  VDUQ+5
  27     lda  #0
  28     rol
  29     sta  VDUQ+6
  30 
  31 * Y-coordinate in VDUQ+7,+8  1024*3/16=192
  32     ldx  VDUQ+7
  33     ldy  VDUQ+8
  34     lda  :YLoMul3Div16,x
  35     clc
  36     adc  :YHiMul3Div16,y
  37     sta  VDUQ+7
  38     stz  VDUQ+8
  39     rts
  40 
  41 :XHiMul7Div32
  42 ]X    =   0
  43     lup  1280/256
  44     db  <]X*7/32
  45 ]X    =   ]X+256
  46     --^
  47 
  48 :XLoMul7Div32
  49 ]X    =   0
  50     lup  256
  51     db  ]X*7/32
  52 ]X    =   ]X+1
  53     --^
  54 
  55 :YHiMul3Div16
  56 ]Y    =   0
  57     lup  1024/256
  58     db  ]Y*3/16
  59 ]Y    =   ]Y+256 
               ===== Page 2 =====
 
  60     --^
  61 
  62 :YLoMul3Div16
  63 ]Y    =   0
  64     lup  256
  65     db  ]Y*3/16
  66 ]Y    =   ]Y+1
  67     --^
```

**Comment by bobbimanners** [comment]
^^ Oh, not tested yet, BTW!

**Comment by bobbimanners** [comment]
I have scaling to 1280x1024 in place now and also clipping out-of-range coordinates so FDraw doesn't scribble where it should not!

**Comment by bobbimanners** [comment]
FDraw is now loaded from file at run time (like a DLL!)
