### ISSUE TITLE
Can't open FDRAW.FAST

### ISSUE THREAD

**Issue by jgharston** [bobbimanners/Applecorn#92]
Hangs on startup displaying Can't open FDRAW.FAST.
Can't find any way to create FDRAW.FAST.
mainmem.ldr.s appears not to terminate the filename in any way:
:FDFILE     STR   'FDRAW.FAST'     ; Filename for FDraw lib
 aux, carry clear->load to main
LOADCODE    PHP                    ; Save carry flag
            STA   :ADDRH       

...so that's going to try and open a file called FDRAW.FAST088D(A....

**Comment by bobbimanners** [comment]
I made this into a separate loadable blob because linking it in directly only works in Merlin-32 (not Merlin-16).

The FDraw lib is in a separate subdir.  You can build it as follows:

```
cd fdraw
merlin32 -v FDRAW.S
```

And then stick it on the disk image so Applecorn can load it at startup.

I probably should make this optional, so if it is not found we just don't support graphics.

**Comment by bobbimanners** [comment]
Oh and the filename is a Pascal string (`STR`) which has a length byte as the first char.  (So no null termination.)

**Comment by bobbimanners** [comment]
Incidentally, if you grab the latest `applecorn.po` disk image then `FDRAW.FAST` should be there (and everything should 'just work').

**Comment by bobbimanners** [comment]
@jgharston Did you get this working?  If so, I will close the ticket.

**Comment by jgharston** [comment]
I'll try at work tomorrow. Using phobile mone at the mo.

**Comment by bobbimanners** [comment]
OK fair enough.  Phone sounds painful!!  The .PO should have the `FDRAW.FAST` lib already.

The only modification I made to 'stock' FDraw is to set the ORG to $9400.

**Comment by bobbimanners** [comment]
The latest code also loads `FONT.DAT`.  That is on the latest `applecorn.po` also.

**Comment by bobbimanners** [comment]
Assumung this is resolved.
